#pragma once

#include "adabs/gasnet_config.h"

namespace adabs {

namespace impl {

gasnet_handlerentry_t *callbacks;

/*const int MATRIX_BASE_INIT_GET = 128;
const int MATRIX_BASE_INIT_SET = 129;

const int MATRIX_BASE_SET = 132;
const int MATRIX_BASE_GET = 133;
const int DISTRIBUTED_MATRIX_BASE_DELETE = 134;
const int DISTRIBUTED_MATRIX_BASE_REMOVE = 135;
const int DISTRIBUTED_MATRIX_BASE_DELETE_ALL = 136;
const int DISTRIBUTED_MATRIX_BASE_ENABLE_REUSE_ALL = 137;
const int DISTRIBUTED_MATRIX_BASE_REUSE = 138;
const int DISTRIBUTED_MATRIX_BASE_REUSE_REPLY = 139;
const int DISTRIBUTED_MATRIX_BASE_ENABLE_REUSE_ALL_REPLY = 140;
const int DISTRIBUTED_MATRIX_BASE_RESET_USE_FLAG = 141;
const int DISTRIBUTED_MATRIX_BASE_SCATTER = 142;*/

//const int MEMORY_MANAGEMENT_MALLOC = 143;
//const int MEMORY_MANAGEMENT_MALLOC_REPLY = 144;
//const int MEMORY_MANAGEMENT_FREE = 145;

const int SET_RETURN_MARKER = 128;

const int MEMCPY = 129;

const int PGAS_ADDR_CHECK_GET_ALL = 144;
const int PGAS_ADDR_GET_UNINIT = 145;
const int PGAS_ADDR_GET = 146;
const int PGAS_ADDR_SET = 147;

const int COLLECTIVE_ALLOC_BROADCAST = 148;
const int REMOTE_COLLECTIVE_ALLOC = 149;
const int REMOTE_COLLECTIVE_FREE = 150;
const int REMOTE_COLLECTIVE_ALLOC_REPLY = 151;

const int COLLECTIVE_PGAS_ADDR_SET = 152;


const int NUMBER_OF_CALLBACKS = 11;

}

}
